services:
  libraryapp.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
        - "5280:8080"
        - "5281:8081"
    volumes:
        - ~/.aspnet/https:/https
    depends_on:
      - postgres

  postgres:
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=PASSWORD_TEST1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=library
    ports:
      - 5432:5432
       
