# This is a generated file. Not intended for manual editing.
services:
  libraryapp.api:
    build:
      context: "C:\\Users\\Henrique\\Desktop\\TrabalhoLibrary\\LibraryApp"
      dockerfile: "LibraryApp.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/LibraryApp.Api.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net9.0/LibraryApp.Api.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "libraryappapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\Henrique\\Desktop\\TrabalhoLibrary\\LibraryApp\\LibraryApp.Api:/app:rw"
    - "C:\\Users\\Henrique\\Desktop\\TrabalhoLibrary\\LibraryApp:/src:rw"
    - "C:\\Users\\Henrique\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
